config/routes.rb
Rails.application.routes.draw do
  root 'links#index'
  
  devise_for :users
  resources :links

end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title QualityAction
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - flash.each do |name, msg|
      = content_tag(:div, msg, class: "alert alert-#{name}")
    = yield

app/views/links/_form.html.haml
= form_for(@link) do |f|
  - if @link.errors.any?
    #error_explanation
      %h2
        = pluralize(@link.errors.count, "error")
        prohibited this link from being saved:
      %ul
        - @link.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :url
    %br/
    = f.text_field :url
  .actions
    = f.submit

app/views/links/edit.html.haml
%h1 Editing Link
= render 'form'
= link_to 'Show', @link
|
\#{link_to 'Back', links_path}

app/views/links/index.html.haml
%p#notice= notice
%h1 Listing Links
%table
  %thead
    %tr
      %th Title
      %th Url
      %th{:colspan => "3"}
  %tbody
    - @links.each do |link|
      %tr
        %td= link.title
        %td= link.url
        %td= link_to 'Show', link
        %td= link_to 'Edit', edit_link_path(link)
        %td= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Link', new_link_path

app/views/links/new.html.haml
%h1 New Link
= render 'form'
= link_to 'Back', links_path

app/views/links/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @link.title
%p
  %strong Url:
  = @link.url
= link_to 'Edit', edit_link_path(@link)
|
\#{link_to 'Back', links_path}